# Generated by Django 5.2.6 on 2025-10-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_product_options_alter_sale_options'),
    ]

    operations = [
    ]
