# Generated by Django 5.2.6 on 2025-10-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20251009_1819'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='ecommerce_category',
        ),
    ]
